#!/bin/bash

# Configuration

[ -v CONFIGURATION_COMPLETE ] && echo "Configuration already complete, skipping" && { return  >/dev/null 2>&1 || exit ; } 

: ${CONFIGURATION_DISPLAY:=true}
# uncomment to force these scripts to display configuration information
###CONFIGURATION_DISPLAY=true

APPLICATION_NAME=resilientnet
APPLICATION_ROUTING_ADDRESS_PREFIX=101st_Airborne_Division
APPLICATION_ROUTING_ADDRESS_FQN=${APPLICATION_ROUTING_ADDRESS_PREFIX}/506th_Parachute_Infantry_Regiment/HQ


OPENSHIFT_DOMAIN=rhsademo.net
#OPENSHIFT_DOMAIN=open.paas.redhat.com
OPENSHIFT_MASTER=master.${OPENSHIFT_DOMAIN}
#OPENSHIFT_MASTER=${OPENSHIFT_DOMAIN}
OPENSHIFT_APPS=apps.${OPENSHIFT_DOMAIN}
#OPENSHIFT_APPS=int.${OPENSHIFT_DOMAIN}
OPENSHIFT_USER=mepley
OPENSHIFT_PASSWORD=${OPENSHIFT_RHSADEMO_USER_PASSWORD_DEFAULT}
#OPENSHIFT_PASSWORD=${OPENSHIFT_ITPAAS_USER_PASSWORD_DEFAULT}
OPENSHIFT_PROJECT=${OPENSHIFT_USER}-${APPLICATION_NAME}
OPENSHIFT_OUTPUT_FORMAT=json

OPENSHIFT_PROJECT_DISPLAY_NAME=${OPENSHIFT_PROJECT}

# capture these configuration items from the user's environment
REDHAT_SUBSCRIPTION_USER=${REDHAT_SUBSCRIPTION_USER_MEPLEY}
REDHAT_SUBSCRIPTION_USER_PASSWORD=${REDHAT_SUBSCRIPTION_USER_MEPLEY_PASSWORD}
REDHAT_SUBSCRIPTION_USER_POOL_ID=${REDHAT_SUBSCRIPTION_USER_MEPLEY_POOL_ID}
CONTENT_SOURCE_DOCKER_IMAGES_RED_HAT_REGISTRY=registry.access.redhat.com

if [ "$CONFIGURATION_DISPLAY" != "false" ]; then
echo "Configuration_____________________________________"
echo "	APPLICATION_NAME                     = ${APPLICATION_NAME}"
echo ""
echo "	OPENSHIFT_MASTER                     = ${OPENSHIFT_MASTER}"
echo "	OPENSHIFT_APPS                       = ${OPENSHIFT_APPS}"
echo "	OPENSHIFT_PROJECT                    = ${OPENSHIFT_PROJECT}"
echo "	OPENSHIFT_USER                       = ${OPENSHIFT_USER}"
echo "	OPENSHIFT_PASSWORD                   = `echo ${OPENSHIFT_PASSWORD} | md5sum` (obfuscated)"
echo "	OPENSHIFT_OUTPUT_FORMAT              = ${OPENSHIFT_OUTPUT_FORMAT}"
echo "	REDHAT_SUBSCRIPTION_USER             = ${REDHAT_SUBSCRIPTION_USER}"
echo "	REDHAT_SUBSCRIPTION_USER_PASSWORD    = `echo ${REDHAT_SUBSCRIPTION_USER_PASSWORD} | md5sum` (obfuscated)"
echo "	REDHAT_SUBSCRIPTION_USER_POOL_ID     = ${REDHAT_SUBSCRIPTION_USER_POOL_ID}"
echo "	CONTENT_SOURCE_DOCKER_IMAGES_RED_HAT_REGISTRY = ${CONTENT_SOURCE_DOCKER_IMAGES_RED_HAT_REGISTRY}"
echo "____________________________________________________________"
fi

CONFIGURATION_COMPLETE=true